### ISSUE TITLE
BUG: `require()` looks to project root _first_ irrespective of `NODE_PATH`.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#107]
### Problem

Looking more at https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders it appears if we have:

```
ROOT/
  node_modules/
    foo@wrong-version
    ARCHETYPE/
      configs/
        file.js -> `require("foo")`
    ARCHETYPE-dev/
      node_modules/
        foo@right-version
```

That despite placing `NODE_PATH` with archetype first, that `ROOT/node_modules/foo` is resolved for `require("foo")`. This is a problem because we want archetype node_modules to win.

**Notes**:

* This does _not_ affect our `PATH` mutations -- archetype .bin wins.
* This does _not_ affect tasks + dependency in the prod archetype.
* Manifest only when have separate dev archetype. The reason is that require looks in
  current directory of JS file on down, so if config file is in prod archetype
  it looks there first before traversing down the directory.

### Task

* [ ] Make archetype node_modules win.

### Research

* How Node.js initializes paths in order of lookup preference: https://github.com/nodejs/node/blob/master/lib/module.js#L456-L484 This is then exposed via: https://github.com/nodejs/node/blob/master/lib/internal/module.js
* Require Hacking Survey: http://stackoverflow.com/questions/24190043/proxyquire-rewire-sandboxedmodule-and-sinon-pros-cons
* Update `module.paths` manually. AKA https://github.com/patrick-steele-idem/app-module-path-node
* Resolution order within the webpack config:

    ```js
    [ '/Users/rroemer/scm/wm/getting-started/node_modules/@walmart/electrode-archetype-react-app/config/webpack/partial/node_modules',
      '/Users/rroemer/scm/wm/getting-started/node_modules/@walmart/electrode-archetype-react-app/config/webpack/node_modules',
      '/Users/rroemer/scm/wm/getting-started/node_modules/@walmart/electrode-archetype-react-app/config/node_modules',
      '/Users/rroemer/scm/wm/getting-started/node_modules/@walmart/electrode-archetype-react-app/node_modules',
      '/Users/rroemer/scm/wm/getting-started/node_modules/@walmart/node_modules',
      '/Users/rroemer/scm/wm/getting-started/node_modules',
      '/Users/rroemer/scm/wm/node_modules',
      '/Users/rroemer/scm/node_modules',
      '/Users/rroemer/node_modules',
      '/Users/node_modules',
      '/node_modules' ]
    ```

### OPTION ONE - Add/use `ARCHETYPE-dev/require.js` file.

Provide a straight shim of `require` from a well-known file in the dev archetype, so that calling it goes down dev archetype hierarchy.

Pros:

* Does _not_ mutate require or module.paths or anything.
* Lightest weight solution!

Cons:

* Have to rewrite `require()'s when using dev packages.
* Have to have boilerplate require.js file. (but should be part of `builder-support --gen-dev`)

```js
// ARCHETYPE-dev/require.js
module.exports = require;

// Meanwhile, in archetype JS files...
// ARCHETYPE/config/webpack/webpack.config.js
"use strict";

{
  babel: require("ARCHETYPE-dev/require").resolve("babel-loader")
}
```

### OPTION TWO - Mutate `module.paths`

This does what the `NODE_PATH` mutation intended to do.

Pros:

* Cascades down to nested imports.
* Is a NOP when used without builder / environment mutation.

Cons:

* Need to insert code snippets in top-level required files.
* Heavyweight / mutating. (Could wrap a require-like method that mutates, then unmutates...)

```js
// builder-client/register.js
module.exports = function () {
  var path = require("path");

  // TODO: THIS ACTUALLY COMES FROM ENVIRONMENT.
  var archRoots = [
    "ARCHETYPE",
    "ARCHETYPE-dev"
  ].map(function (arch) {
    return path.join(path.dirname(require.resolve(path.join(arch, "package.json"))), "node_modules");
  });

  module.paths = [].concat(
    archRoots,
    module.paths
  );
};

// Meanwhile, in archetype JS files...
// ARCHETYPE/config/webpack/webpack.config.js
"use strict";

require("builder-client").register();
```

### OPTION THREE - Provide alternate `require`, `require.resolve`

This does what the `NODE_PATH` mutation intended to do.

Pros:

* Non-mutating.

Cons:

* Need to insert code snippets for all archetype `require`, `require.resolve` statements.
* Doesn't cascade down to nested imports.

```js
// builder-client/require.js
module.exports = function (modPath) {
  var path = require("path");

  if (/*isrelative*/) { return require(modPath); }

  var mod;

  // TODO: THIS ACTUALLY COMES FROM ENVIRONMENT.
  [
    "ARCHETYPE",
    "ARCHETYPE-dev"
  ].forEach(function (arch) {
    if (mod) { return; }

    // Try to import from the archetype.
    var archPath path.join(path.dirname(require.resolve(path.join(arch, "package.json"))), "node_modules");
    try {
      mod = require(path.join(archPath, modPath));
    } catch (err) { /*swallow*/ }
  });

  // Fall back to normal module.
  return mod || require(mod);
};

module.exports.resolve = /*TODO: Return resolved path*/;

// Meanwhile, in archetype JS files...
// ARCHETYPE/config/webpack/webpack.config.js
"use strict";

module.exports = function (babel) {
  return function (config) {
    return mergeWebpackConfig(config, {
      module: {
        loaders: [{
          // ... OLD STUFF ...
          loader: require("builder-client").require.resolve("babel-loader"),
          query: babel
        }]
      }
    });
  };
};
```

**Comment by shakefon** [comment]
I would be in favor of option 1, **Mutate `module.paths`**.

Reasoning being:
* I prefer the idea that the solution cascades to nested imports, as I believe without this we may continue to see issues.
* I think the implementation in each archetype JS file is cleaner versus the alternative option.
* The register hook is also familiar to those coming with experience of the babel world, which will be a large crossover for users of builder, I would imagine.

I share your view that option one is quite heavyweight and is a mutating option which isn't always ideal, but I still feel it's the better option.

**Comment by jchip** [comment]
any kind of mutating/messing with NodeJS require/module paths feels iffy.

How about:

`archetype-dev/require.js`:

```js
module.exports = function (mod) {
	return require(mod);
};
```

`archetype/config.js`:

```js
var babelLoader = require("archetype-dev/require")("babel-loader");
```

**Comment by ryan-roemer** [comment]
@jchip -- That's a pretty good idea! As an updated example, we'd at a minimum need:

```js
module.exports = function (mod) {
  return require(mod);
};

module.exports.resolve = function (mod) {
  return require.resolve(mod);
}
```

**Comment by chaseadamsio** [comment]
:+1: from me on @jchip's solution.

**Comment by coopy** [comment]
To clarify: Does option one work because you are going through the `require` exposed in the `ARCHETYPE-dev` module, which looks at `ARCHETYPE-dev/node_modules` first?

I'm in favor of that option, since it's light on code and actually is pretty straightforward once you understand it (provided I do understand it!)

Please add a comment to the top of `ARCHETYPE-dev/require.js` explaining what it's used for, and why it works.

**Comment by ryan-roemer** [comment]
@coopy -- Resolution happens from the file in which the `require` resides, then "down the path tree". So by exposing the dev archetype's `require` we start in the _dev archetype_ when traversing down the tree. I'll add a large section in the README for this pattern if we implement this option.

**Comment by shakefon** [comment]
I change my vote to the new Option One. Superb contribution @jchip
