### ISSUE TITLE
Babel plugin for "module pattern" for application dependencies from archetype via ES-next imports.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#111]
## Background

For normal node code, we can get application deps from the archetype using something like:

``` js
var _ = require("<archetype>/require")("lodash");
```

See: https://github.com/FormidableLabs/builder/blob/master/README.md#node-require-resolution-and-module-pattern

However, this doesn't work for ES-next imports like:

``` js
import _ from "lodash";
```

because those get translated to:

``` js
"use strict";

var _lodash = require("lodash");

var _lodash2 = _interopRequireDefault(_lodash);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

And we don't have specific control over the `require("lodash");` portion.

## Task
- [ ] Write a babel plugin to make the module pattern from prod / dev archetype dependencies available to babel transpiled code.

## Potential Implementation

A configuration approach that allows abitrary rewriting of the ultimate `require` function call to something different. Uses a key token in the import source to denote when to rewrite `require` and _what_ to rewrite with.

```js
// .babelrc
{
  "plugins": [
    ["NEW_MODULE_O_REWRITENESS", {
      DEV_ARCHETYPE: "require(\"<archetype>/require\")"
    }]
  ]
}

// src/foo.js
import _ from "DEV_ARCHETYPE/lodash";
```

/cc @coopy

**Comment by joncursi** [comment]
Really looking forward to seeing this issue resolved. I've been playing with builder for a few days now, and I am very impressed! This issue is the only blocker I have before I transition my npm-based repositories over to Builder. Deciding to hold off for now because I don't want to have to stray away from ES6 imports (or more generally, change any my application code) to get packages to import properly.

Any ETA on this plugin?

**Comment by ryan-roemer** [comment]
@joncursi -- Great to hear the interest! So just to check: your scenario would have the `.babelrc` be part of the production archetype and all of your babel dependencies would be part of the development archetype?

We've internally made progress on this front working on some client projects too if you have the canonical "potential problem case".

/cc @exogen (who can likely comment once we get your specific use cases...)

**Comment by joncursi** [comment]
Exactly. My use-case requires a "production" archetype for managing npm "dependencies" and a "development" archetype for managing "devDependencies" within `package.json`.

At a high-level, this is a list of shared config among my repositories that I would love to consolidate down into these two archetypes:

* Production archetype
  * Standardized `.babelrc` config
  * Standardized production packages (i.e. react, immutable, redux, etc.)

* Development archetype
    * Babel preset and plugin packages
    * Standardized `.gitignore` and `.gitattributes` configs
    * Standardized development packages, (i.e. test runner / assertion / coverage / etc. for running test suites)
    * Standardized `npm run <_>` scripts
    * Standardized third-party config files
      * Standardized `.codeclimate.yml` config
      * Standardized `.eslintignore` and `.eslintrc.yml` configs
        * ESLint config and plugin packages
      * Standardized `circle.yml` config (or any other CI config, with the ability to override repo-specific variables)
      * Standardized `mocha.opts` config

It looks like any config that touches `package.json` is already fully manageable with builder, with the ability to over-ride said config on a per-project basis. However, I'm not sure if this is available for other configs, such as the third-part configs, that are managed outside of `package.json` in their own files. Is this possible?

My outstanding wants:
* Continue to use ES6 import syntax in my business logic (this issue tracker)
* Being able to pull in a third-party config file from the archetype, i.e. `circle.yml`, merge this with project-specific overrides. Here's an example:

```yml
// archetype circle.yml - general stuff
...
checkout:
  post:
    - git submodule update --init
machine:
  timezone:
    America/New_York
  node:
    version: 6.2.2
...
```

```yml
// root circle.yml - project-specific stuff
...
dependencies:
  override:
    - some unique command here
...
```

**Comment by ryan-roemer** [comment]
@joncursi -- Thanks for that excellent breakdown!

So, a few thoughts to hopefully start ticking things off your list:

# The main thing

## es6 imports

Let @exogen and I mull over this more. My hunch is that a babel plugin may be appropriate and hopefully not too much work... (???)

# All the other stuff

## babelrc

I _think_ you might be able to get away with a `.babelrc` just in the dev archetype if you have **all** the dependencies also in the dev archetype. So something like:

```js
// == PROJECT ==
// my-project/.babelrc
{
  "extends": "my-archetype-dev/config/babelrc/.babelrc"
}

// == PROD ARCHETYPE ==
// my-archetype/package.json
"scripts": {
  // **ALL** of the script tasks for builder. A `-dev` archetype cannot supply
  // those...
}

// == DEV ARCHETYPE ==
// ... however, a `-dev` archetype _can_ provide config files.
// my-archetype-dev/config/babelrc/.babelrc
{
  "presets": ["react", "react-latest-hotness"],
  "plugins": ["lodash"]
}

// my-archetype-dev/package.json
"dependencies": {
  "babel-cli": "^6.6.5",
  "babel-core": "^6.10.4",
  "babel-loader": "^6.2.4",
  "babel-plugin-lodash": "^3.1.2",
  "babel-preset-react": "^6.5.0",
  "babel-preset-react-latest-hotness": "^1.9.0",
  // ...
}
```

## Standardized production / dev packages

Should be available via the module pattern.

## Standardized `builder run` scripts tasks.

Fully supported, with easy ability to override.

## Dev Configs

Many configs in a repo have to be a "real" file. Even the `.babelrc`, although that can be an extension of something from the archetype.

Easy cases:

- `.eslintrc`: Do an `extends` of the archetype in a real file. Override per-project in that file as needed.

Medium cases:

- `mocha.opts`: You can configure the `package.json:scripts` command to point to the one in the archetype.

Potentially harder cases:

- `.gitignore`, `.gitattribute`: These may need to be real files in each repo unless there's an "extends" analogue.
- `.eslintignore`: Not sure if extendable like `.eslintrc`.
- `.codeclimate.yml`, `circle.yml`: Not sure if extendable.

### Random potential solutions

#### Local `try/catch` includes.

One hard part of npm workflows is that shell commands can't easily swap file paths in shell commands to other things. And parsing real shell is a hard task to get right, which we don't do in Builder. _But_ there are techniques we've seen successfully used in projects like the following:

```js
// == ARCHETYPE ==
// my-archetype/package.json
"scripts": {
  "build": "webpack --config my-archetype/config/webpack/webpack.config.js"
}

// my-archetype/config/webpack/webpack.config.js
var config = {
  // ... webpack stuff.
};

// Allow a project root magic file to override!
try {
  config = require(path.join(process.cwd(), "config/webpack/webpack.config.js"))(config);
} catch (err) {
  // ignore
}

module.exports = config;

// == PROJECT ==
// my-project/config/webpack/webpack.config.js
module.exports = function (baseConfig) {
  // mutate base config to heart's desire...

  return baseConfig;
};
```

So that a root project **may** have an override in a special place that if there changes thing. But if in this example `my-archetype/config/webpack/webpack.config.js` isn't present, then the default archetype config totally controls...

This technique only works when you're in real Node.js for a config. But quite a number of things are...

#### Change scripts to point to local version.

The opposite way to do the above without the `try/catch` is to change the underlying scripts with an override:

```js
// == ARCHETYPE ==
// my-archetype/package.json
"scripts": {
  "build": "webpack --config my-archetype/config/webpack/webpack.config.js"
}

// my-archetype/config/webpack/webpack.config.js
module.exports = {
  // ... webpack stuff.
};

// == PROJECT ==
// my-project/package.json
"scripts": {
  "build": "webpack --config config/webpack/webpack.config.js"
}

// my-project/config/webpack/webpack.config.js
var baseConfig = require("my-archetype/config/webpack/webpack.config");

// mutate base config to heart's desire...

module.exports = baseConfig;
```

... but you've now overridden the base scripts tasks, which _may_ have more complexities than just pointing to a config file.

#### Bootstrap Scripts command

One other thought for the harder cases is having a "bootstrap" command in the archetype to copy fresh static "special" config files like these to the root project, overwriting what was previously there. But, of course, then there is no "per-project" deviation.

And of course, if any of these files _can_ be like a symlink or something, you would deterministically know the path to them as long as the archetype is a top-level package.json dependency. (It will always be at top-level of `node_modules`, flattening or not).

**Comment by ryan-roemer** [comment]
@joncursi @exogen -- Have WIP for `babel-plugin-replace-require` going at https://github.com/FormidableLabs/babel-plugin-replace-require/compare/feature-addTransform

Looking good so far I think, but then again, this is my first babel plugin 😛

**Comment by ryan-roemer** [comment]
UPDATE -- Babel plugin should hopefully be done soon.

In the meantime, I've released a sister webpack plugin to make the module pattern actually _work_ with webpack since it won't in the form Node.js can handle -- https://github.com/FormidableLabs/webpack-alternate-require-loader

**Comment by ryan-roemer** [comment]
UPDATE -- https://github.com/FormidableLabs/babel-plugin-replace-require has been released! I've still got to update the docs for:

* Update per `babel-plugin-replace-require`
* Update per `webpack-alternate-require-loader`
* Revise examples to be compatible with `webpack-alternate-require-loader`.
* Remove webpack config modules mutation for dev archetype.


But all the pieces are now available and published.

@joncursi -- Let me know if there are any hiccups you hit!

**Comment by joncursi** [comment]
@ryan-roemer awesome! I will circle back to this after Tgiving!
