### ISSUE TITLE
Suppress task logging for `help` and `version` actions

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/builder#127]
This is very excessive:
```
$ builder -v
[builder:config:environment] {"cwd":"/Users/brianbeck/Projects/Tests/test-builder-log","dir":"/Users/brianbeck/Projects/Formidable/builder/lib"}
[builder:config] Unable to load config file: .builderrc
[builder:local-detect] Switched to local builder at: /Users/brianbeck/Projects/Tests/test-builder-log/node_modules/builder/bin/builder-core.js
[builder:builder-core:start:15907] Started: version
3.0.0-beta.1
[builder:builder-core:end:15907] Task: version ended normally
```

...and `help` would be nicer without the surrounding noise as well. For `-v`/`version` this can be overridden with `--log-level` or `--quiet`, but you can't do the same with `help`.

Even though builder runs `version` and `help` as tasks like any other, that's an implementation detail and IMO the CLI would be nicer (and much more like other tools) without the noise.

**Comment by ryan-roemer** [comment]
Agreed. We can probably even do this at the `args.js` level, maybe do `log-level` critical if not otherwise set from CLI to effectively suppress?
