### ISSUE TITLE
[BUG] Windows: MinGW/Git Bash/Etc. use `PATH` env var instead of `Path` like cmd does.

### ISSUE THREAD

**Issue by rhbecker** [FormidableLabs/builder#142]
I see the above error with the following setup:

- builder v3.2.2
- node v6.11.0
- windows 10
- executing in git-bash, cygwin, etc.

These same issues **do not** occur via cmd.

If you have such an environment, you can repro via `npm run builder:check`, which yields ...

- 78 passing
- 8 pending
- 11 failing

So far, I have no explanation - only observations ...

All 11 failing tests call an npm script defined to include ...
`"node test/server/fixtures/echo.js ..."`
... but there are 4 tests that pass with the same script.

The difference is that the 11 failing ones invoke the script via `run` or `concurrent`, while the 4 passing ones invoke with `envs`.

Don't pass:
- `run({argv: ["node", "builder", "run", "echo", ...]}, ...});`
- `run({argv: ["node", "builder", "concurrent", "echo", ...]}, ...});`

Pass:
- `run({argv: ["node", "builder", "envs", "echo", ...]}, ...});`

So, you might think any script invoked via `run` that calls `node whatever` might fail, but that is not the case. The `"runs with --setup"` test passes. It defines an npm script ...

`"bar": "node test/server/fixtures/repeat-script.js 5 BAR_TASK >> stdout.log"`

... which it calls via ...

`run({argv: ["node", "builder", "run", "bar", "--setup=setup"]}, ...});`

**Comment by rhbecker** [comment]
FWIW, I just tried reverting to builder v2.10.1 and that version seems to work with the tasks I'm actually trying to execute, in the git-bash / cygwin on windows 10 environment.

**Comment by dusura** [comment]
A fix for this would be nice. Builder is not usable on Windows (Windows 7 in my case). As @rhbecker says, a number of tests fail on Windows.

**Comment by ryan-roemer** [comment]
Can folks give me examples of real CLI commands that are failing? (The tests are a bit hacked-up / mocked-out).

I've now got a win7 VM and will try and dig into this today and next week...

**Comment by ryan-roemer** [comment]
Weird. All of `npm run builder:check` passed on my win7 vm in `cmd` with node `v6.11.4`. Do I need to do cygwin or something?

**Comment by ryan-roemer** [comment]
OK, reproduced in git-bash. It reproduces on CLI too.

For scripts:

```js
    "echo": "echo %m%",
    "bounce": "node bin\\builder.js run echo",
```

## Internal spawn of an executable `node`

The command:

```
$ node bin/builder.js envs bounce "[{\"m\":1},{\"m\":2}]"
```

Passes on `cmd`, but fails in git-bash with:

```
'node' is not recognized as an internal or external command,
operable program or batch file.
[builder:proc:end:1] Command: node bin\builder.js run echo, Environment: {"m":1}
[builder:proc:error] Code: 1, Command: node bin\builder.js run echo, Environment
: {"m":1}
```

## No spawn

The command:

```
$ node bin/builder.js envs echo "[{\"m\":1},{\"m\":2}]"
```

Works fine in both `cmd` and git-bash.

**Comment by ryan-roemer** [comment]
Haha, it's cuh-razy time here. The narrow bug is a matter of "where is PATH in the OS shell?"

- On Mac/Linux, it's `process.env.PATH`
- On Windows + cmd it's `process.env.Path` (Even though both `echo %PATH%` and `echo %Path` work the same on cmd shell, it's _only_ `Path` in node land)
- On Windows + MinGW / presumably other stuff it's `process.env.PATH`

The current logic detects "is Windows?" and uses `Path`. My plan is to update the code so if Windows is detected, search + update both `Path` _and_ `PATH`
