### ISSUE TITLE
Tracking: Using spawn vs. exec as underlying process mechanism

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/builder#20]
In investigating FormidableLabs/radium#420, I'm beginning to suspect that the users' shell configuration is a contributing factor. For example, you can configure your shell in a strict mode so that if any command fails in a `cmd1 || cmd2` chain, the whole command still fails, as if they were joined with `&&`. It's possible these people have some global setting that's causing the `||` to fail (yes, even though NPM attempts to run your script with plain old `sh`).

Anyway, whether or not that is the issue, I dug into how `npm` runs scripts, and found that [they use `spawn`](https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib/utils/lifecycle.js#L224) (they wrap Node's `spawn` slightly). In order to not have to parse the command, they run `sh -c` which takes the shell command to run as a string.

While I'm fine with `exec`, I thought I'd bring this back up because it's a difference in how Builder runs your script vs. NPM – and I anticipate that difference being a source of issues and confusion in a future where Builder is used more widely.

(We can put this off for now, just thought I'd add it as a TODO.)

**Comment by ryan-roemer** [comment]
@exogen -- Yep, I'm familiar with the internals of `npm run` and they do use `spawn`.

We'll keep this issue open and icebox'ed for tracking. Thanks!
