### ISSUE TITLE
README: `npm:`-prefixed tasks in "I Give Up" section

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#21]
Need to add a note to remove `npm:` from tasks and merge in with rest of root tasks.

**Comment by chaseadamsio** [comment]
I think I missed the removal of `npm:` from the tasks, was there something specific that triggered that?

**Comment by ryan-roemer** [comment]
It's just for the documentation for the section of if you are abandoning builder altogether

**Comment by chaseadamsio** [comment]
:+1:
