### ISSUE TITLE
Dependency in archetype does not resolve when postinstalling as dependency

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/builder#24]
## Overview

`npm install` in [`victory-voronoi`](https://github.com/FormidableLabs/victory-voronoi) fails.

`victory-voronoi` depends on `victory-animation`, which runs a [postinstall script](https://github.com/FormidableLabs/victory-animation/blob/master/package.json#L17): `builder run npm:postinstall`, which fails because `rimraf` can't be found.

`victory-animation` uses the `builder-react-component` archetype, which `rimraf` [is part of](https://github.com/FormidableLabs/builder-react-component/blob/master/package.json#L63).

`rimraf` also happens to be a dependency of `victory-voronoi`, but I assume it isn't installed yet at the time `victory-animation` runs its' postinstall script.

### NPM and Node versions

```
$ npm -v
2.14.7
$ node -v
v4.2.2
```

### NPM debug output
```
> victory-animation@0.0.6 postinstall /Users/per/dev/formidable/victory-voronoi/node_modules/victory-animation
> npm run build-lib

|
> victory-animation@0.0.6 build-lib /Users/per/dev/formidable/victory-voronoi/node_modules/victory-animation
> npm run clean-lib && babel --stage 0 src -d lib

/
> victory-animation@0.0.6 clean-lib /Users/per/dev/formidable/victory-voronoi/node_modules/victory-animation
> rimraf lib

sh: rimraf: command not found

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/per/.nvm/versions/v4.2.2/bin/node" "/Users/per/.nvm/versions/v4.2.2/bin/npm" "run" "clean-lib"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! victory-animation@0.0.6 clean-lib: `rimraf lib`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the victory-animation@0.0.6 clean-lib script 'rimraf lib'.
npm ERR! This is most likely a problem with the victory-animation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf lib
```

/cc @exogen @ryan-roemer

**Comment by ryan-roemer** [comment]
@coopy -- Please open these issues in upstream victory relevant repo first, and then have @boygirl or @exogen open against builder after an investigation shows it's actually builder at issue. :wink: 

In this case, there is no builder involved:

```
$ npm install victory-voronoi
```

Installs: `victory-voronoi@0.0.5` and `victory-animation@0.0.6`, neither of which use `builder` yet

**SIDE NOTE**: @boygirl @exogen @coopy @colinmegill -- Our Victory repos are not git tagging and pushing. `victory-voronoi` and `victory-animation` are missing **a lot** of tags. I suspect others. Can one of you open an issue in **each** victory repo to ensure all tags are present for all npm versions?

**Comment by boygirl** [comment]
@coopy I think this is an issue with the voronoi package itself. I just PR'd a fix
https://github.com/FormidableLabs/victory-voronoi/pull/2

**Comment by boygirl** [comment]
@ryan-roemer I'm on the tags issues

**Comment by coopy** [comment]
@ryan-roemer I didn't think to check which version of `victory-animation` that `victory-voronoi` depends on. Sorry for opening in the wrong repo!
