### ISSUE TITLE
Feature: `builder envs TASK ENV_VAR2=foo ENV_VAR2=bar`

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#29]
Instead of concurrently running lots of npm `scripts` tasks, instead split concurrent processes on a list of environmental variables to be parsed and passed in to `exec` environment in an OS-agnostic way.

Use case: Selenium tests and `ROWDY_SETTINGS`

```sh
$ builder envs test-func \
  ROWDY_SETTINGS="local.phantomjs" \
  ROWDY_SETTINGS="local.firefox" \
  ROWDY_SETTINGS="sauceLabs.chrome_43_Windows_2012_R2_Desktop" \
  ROWDY_SETTINGS="sauceLabs.firefox_38_Windows_2012_R2_Desktop" \
  ROWDY_SETTINGS="sauceLabs.IE_9_Windows_2008_Desktop" \
  ROWDY_SETTINGS="sauceLabs.IE_10_Windows_2012_Desktop" \
  ROWDY_SETTINGS="sauceLabs.IE_11_Windows_2012_R2_Desktop"
```

OR

```sh
$ builder envs test-func \
  '[ { "ROWDY_SETTINGS":"sauceLabs.IE_8_Windows_2008_Desktop" }, \
     { "ROWDY_SETTINGS":"sauceLabs.IE_9_Windows_2008_Desktop" }, \
     { "ROWDY_SETTINGS":"sauceLabs.IE_10_Windows_2012_Desktop" }, \
     { "ROWDY_SETTINGS":"sauceLabs.safari_7_OS_X_10_9_Desktop" }, \
     { "ROWDY_SETTINGS":"sauceLabs.safari_8_OS_X_10_10_Desktop" }, \
     { "ROWDY_SETTINGS":"sauceLabs.chrome_43_OS_X_10_10_Desktop" }, \
     { "ROWDY_SETTINGS":"sauceLabs.chrome_43_Windows_2012_R2_Desktop" }, \
     { "ROWDY_SETTINGS":"sauceLabs.firefox_9_Windows_2012_R2_Desktop" }, \
     { "ROWDY_SETTINGS":"local.firefox" } ]'
```

Probably leaning toward the latter (JSON string) as:

* Easier to parse command-line wise.
* Can have a multiple environment variables for "one" environment.
* Solves the "no variable" problem. (e.g., do `{}`)

Current strawman:

```sh
$ builder envs \
  --tries=3 \
  --queue=3 \
  --envs-path=FILE_PATH \
  TASK \
  JSON_STRING
```

**Comment by chaseadamsio** [comment]
I think since we're working with Javascript and npm tasks here, a JSON string is acceptable and it seems like, just from my first impression, it's a lot harder to mess up (I could see lots of weird edge cases with multi-line shell arguments.

What are your thoughts on potentially allowing this to be read from a file specified in the command as well (as an alternative to the really long string)? 

My strawman piggyback:

```
$ builder envs \
...
TASK \
JSON_STRING ||  --envs_file=JSON_FILE_PATH
```

**Comment by ryan-roemer** [comment]
@chaseadamsio -- Makes sense. Updated strawman to:

```sh
$ builder envs \
  --tries=3 \
  --queue=3 \
  --envs-path=FILE_PATH \
  TASK \
  JSON_STRING
```

**Comment by chaseadamsio** [comment]
:th
