### ISSUE TITLE
CSS files not included in /lib/

### ISSUE THREAD

**Issue by hartmamt** [FormidableLabs/builder#36]
When I run builder run build, the CSS files I'm importing such as 

```
import './MuiLauncher.css';
```
are not being included with my .js files in the /lib folder.  If this is intentional, any ideas of how I can work around it?  This is commonly done in our UI library.

**Comment by ryan-roemer** [comment]
Can you point us to your project repo or give us more information as to which archetype you're using, if this is a victory component, etc?

Builder alone is just a task runner and doesn't inherently contain things like 'build' etc.

Thanks!

**Comment by hartmamt** [comment]
I gave you access to https://github.com/hartmamt/catalyst-ui.  It is the builder-react-component archetype.  Not a victory component.  Ken Wheeler just mentioned your project to me a few days ago and I've been trying it out.

**Comment by ryan-roemer** [comment]
@boygirl @exogen @alexlande -- Who did the CSS webpack / build stuff for `builder-react-component`?

@hartmamt -- I'm going to be mostly out-of-band / offline until Tuesday of next week, so apologies if I can't devote more attention to this until then.

**Comment by hartmamt** [comment]
This can be closed, PR submitted FormidableLabs/builder-react-component#13.
