### ISSUE TITLE
Feature: builder `ARCHETYPE` + `ARCHETYPE-dev` release support

### ISSUE THREAD

**Issue by chaseadamsio** [FormidableLabs/builder#46]
Builder should come with (or should have a supplementary package) the ability to publish `builder-<archetype>-dev` packages without the archetype maintainer needing to do anything other than the following:

- Specify the archetype dev dependencies
- Specify in their scripts that they want to use it (as a true `postpublish` script for the dependency)

This package / helper should:

- Maintain synchronicity between `<archetype>` and `<archetype>-dev` versions
- Publish the `<archetype>-dev` version

Currently, `builder-react-component` does this, but the actual process should be abstracted out into an easy to consume package to remove any duplicated code and provide a less abrasive workflow for publishing.

**Comment by ryan-roemer** [comment]
Implemented in https://github.com/FormidableLabs/builder-support
