### ISSUE TITLE
builder-cli

### ISSUE THREAD

**Issue by philholden** [FormidableLabs/builder#59]
It might be nice to have a `builder-cli` module like karma-cli and grunt-cli that just points to local builder and warns if it does not find it:

https://github.com/karma-runner/karma-cli/blob/master/bin/karma

I know builder installed globally does look for a local builder. But in some ways I like the fact the karma and grunt cli just fail when they can't find a local install.

Having `builder-cli` would establish that local install is preferred. You could still enable builder to be globally installed to save space but it could warn by saying: 'you are using a globally installed version of builder'

Telling the user to update the path makes it harder to teach people how to install builder in a way that works for both Windows and Linux.

**Comment by chaseadamsio** [comment]
@philholden `builder` itself does that check for you. I had originally suggested this as well, but since `builder` is _pretty_ light-weight, it made sense to do it in `builder` itself as well as provide a fallback to the global version if the user didn't have a local version installed.

[Code](https://github.com/FormidableLabs/builder/blob/master/bin/builder.js#L12)

From `README.md`:

> To help you keep up with project-specific builder requirements, a globally-installed builder will detect if a locally-installed version of builder is available and switch to that instead:

**Comment by ryan-roemer** [comment]
@philholden -- Thanks for the issue.

This is also going to be a topic related to [`builder init`](https://github.com/FormidableLabs/builder/issues/7) because something is going to need to be globally installed for the chicken-or-egg problem. And the strawman is `builder` itself, but it could theoretically be `builder-init` (a separate project).

**Comment by chaseadamsio** [comment]
@ryan-roemer if `builder-init` is on the table, I'd propose the `builder-cli` that we talked about at the beginning of the project, as it will provide a lot more flexibility down the road.

Proposed strawman:

`builder-cli` that is _still_ the thin check that we do in `builder` now, but also has a hook to check for installed plugins (ie, some people may never want to use `builder init`). A manifest could be stored at the `$HOME` level (`.builderplugins`) which would make it really easy to move between diff. machines or have "archetypes" for the `builder-cli` itself.

^ I know this is _super_ meta and very scope creep-ie, but I like it.

**Comment by ryan-roemer** [comment]
@chaseadamsio - hmm, it does seem crazy to have three separate projects / modules for what is ultimately like four or five substantive files.

**Comment by ryan-roemer** [comment]
And I'm not understanding what the split archetypes for global vs local would be for?

My worry is that we are starting to go down the path of becoming grunt or gulp instead of a tightly honed, virtually invisible layer on top of NPM workflows

**Comment by chaseadamsio** [comment]
Archetype probably wasn't the _best_ word to use there, what I meant really was that you could essentially create a configuration file to keep up with what plugins a team is using at a global level. 

I think you could actually just stick with `builder` itself being installed globally and be totally fine.

**Comment by ryan-roemer** [comment]
I'm going to close this issue with the rationale that:

1. `builder` already does do local detection and gets us a lot of the way there with that.
2. `builder` is independently useful on it's own without any archetypes for things like `builder concurrent` and `builder envs` and with the helpful flags of `--setup`, `--tries=NUM`, `--buffer`, etc. as just a simple task runner helper in projects. It would seem very odd to require _two_ separate installs just to use builder like we do in _non_-archetype projects like:
    * https://github.com/walmartlabs/little-loader/blob/master/package.json
    * https://github.com/FormidableLabs/requirepack/blob/master/package.json
