### ISSUE TITLE
BUG: builder envs does not get same base env ($PATH etc.) as builder run on Node 4+

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/builder#63]
If my `test` command is something like `mocha` or `wdio` that comes from `node_modules`, `builder run test` works fine, but `builder envs test --envs-path=envs.json` spits out:

```
/bin/sh: mocha: command not found
```

Builder should start out with whatever `$PATH` additions come standard with `builder run`, then merge in stuff from `envs` on top of that.

(In case it matters: I'm using Builder just for its task running features, without an archetype.)

**Comment by ryan-roemer** [comment]
@exogen -- Can you please create a reproduction for this and point me to it?

For reference, `requirepack` is already using `builder envs` (Just with straight string, not `--envs-paths` at https://github.com/FormidableLabs/requirepack/blob/master/.travis.yml#L48-L69

**Comment by ryan-roemer** [comment]
@exogen -- Also when running `envs` can you log out `process.env.PATH` and paste it in this ticket? Thanks!

**Comment by exogen** [comment]
Sure thing: try cloning this repo: https://github.com/exogen/builder-test

then:

```sh
npm install
npm run test
builder run test
builder envs test '[{ "FOO": 1 }]'
```

`npm run` and `builder run` work, the last one fails.

**Comment by ryan-roemer** [comment]
Does not error and successfully runs for me:

```
$ builder envs test '[{ "FOO": 1 }]'
[builder:config:environment] {"cwd":"/Users/rroemer/scm/fmd/builder-test","dir":"/Users/rroemer/scm/fmd/builder-test/node_modules/builder/lib"}
[builder:config] Unable to load config file: .builderrc
[builder:builder-core:start:2158] Started: envs test
[builder:envs] Starting with queue size: unlimited
[builder:envs] Starting environment {"FOO":1} run for command: mocha
[builder:proc:start] mocha


  0 passing (2ms)

[builder:proc:end:0] mocha
[builder:builder-core:end:2158] Ended normally: envs test
```

**Comment by exogen** [comment]
@ryan-roemer: Hmm, maybe a Node/npm version? 

```sh
$ node -v
v4.2.3
$ npm -v
3.5.2
```

**Comment by exogen** [comment]
@ryan-roemer Works for me with Node v0.12.7 and same npm (3.5.2), so the difference is with Node 4.

**Comment by ryan-roemer** [comment]
Confirmed error:

```
 $ node -v; npm -v
v4.1.2
3.4.0

$ builder envs test '[{ "FOO": 1 }]'
[builder:config:environment] {"cwd":"/Users/rroemer/scm/fmd/builder-test","dir":"/Users/rroemer/scm/fmd/builder-test/node_modules/builder/lib"}
[builder:config] Unable to load config file: .builderrc
[builder:builder-core:start:2386] Started: envs test
[builder:envs] Starting with queue size: unlimited
[builder:envs] Starting environment {"FOO":1} run for command: mocha
[builder:proc:start] mocha
/bin/sh: mocha: command not found
[builder:proc:end:127] mocha
[builder:proc:error] Code: 127, Command: mocha
[builder:builder-core:end:2386] Ended with error: envs test - Command failed: /bin/sh -c mocha
```

**Comment by ryan-roemer** [comment]
Cuhrazy. `_.merge()` works differently for:

```js
      var taskShOpts = _.merge({}, shOpts, { env: taskEnv });
      console.log("TODO HERE taskShOpts", taskShOpts.env);
```

in `0.10`: 

```js
{ MANPATH: '/Users/rroemer/.nvm/v0.10.40/share/man:',
  NOTEBOOK_URL: 'http://localhost:8000',
  rvm_bin_path: '/Users/rroemer/.rvm/bin',
  VIRTUALENVWRAPPER_PROJECT_FILENAME: '.project',
  // ... TONS OF STUFF ...
  NODE_PATH: '/Users/rroemer/scm/fmd/builder-test/node_modules',
  FOO: 1 }
```

vs. `0.4`:

```js
{ FOO: 1 }
```

**CULPRIT**: Different `_.merge()` behavior.

**Comment by ryan-roemer** [comment]
@exogen -- The following code:

```js
      var taskShOpts = _.cloneDeep(shOpts);
      taskShOpts.env = _.extend(taskShOpts.env, taskEnv);
```

appears to work for https://github.com/FormidableLabs/builder/blob/master/lib/runner.js#L231 if you've got a moment to refine that and PR it up...

**Comment by exogen** [comment]
That is nuts, and I think I figured out why. `merge` behaves differently based on the result of `isPlainObject`.

In node 0.12:
```js
> require("lodash").isPlainObject(process.env)
true
```

In node 4:
```js
> require("lodash").isPlainObject(process.env)
false
```

So I think your solution works because `cloneDeep` will turn `env` into a plain object. I can open a PR shortly.
