### ISSUE TITLE
Feature: Option to run all concurrent tasks to completion even on error

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/builder#64]
If using `builder concurrent` to run multiple tests in parallel, or `builder envs` to run something like a build matrix, it would be nice to disable the short-circuiting behavior when one task fails.

Especially in the case of the build matrix, you don't want one environment failing to cancel the whole build – you want to know the full set of results (e.g. imagine if Sauce Labs cancelled your jobs for every other browser just because a test failed in one browser).

**Comment by ryan-roemer** [comment]
Fixed in #69
