### ISSUE TITLE
Feature: Create "builder-react-app" archetype

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/builder#72]
- Base the archetype on the existing infrastructure of https://github.com/FormidableLabs/converter-react.
- Web home: http://converter-react.formidablelabs.com/
- Take notes as you go, as this will be followed by https://github.com/FormidableLabs/builder/issues/60

**Comment by zachhale** [comment]
Todo:

* [ ] expect server.js to be just one file for all environments. Instead, use `builder envs` to run server w/ different env variables
* [ ] write readme
