### ISSUE TITLE
Research: Tooling to make multi-repo updates and create PRs

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/builder#80]
E.g. 
- archetype version bumps
- shared file line edits

Potential: `git-repo-updater` ?

Potential sources of inspiration / tools

- Auto-PRs.
    - Greenkeeper.io
- Git
    - https://github.com/nodegit/nodegit
- Code Modifications
    - https://github.com/facebook/jscodeshift
    - https://github.com/reactjs/react-codemod

**Comment by ryan-roemer** [comment]
Closing as we now have `multibot`
