### ISSUE TITLE
Feature: Allow `builder` to make archetype application dependencies available to upstream components

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#83]
... this is going to be a **long, tough** discussion... Goal - enable builder archetypes to provide _application_ dependencies for:

* [ ] As a frontend import for webpack.
* [ ] As a server-side include by node.

Complexities:

* [ ] Trying to avoid `npm ls` issues from extraneous / missing dependencies.

Ideas:

* [ ] Create a `postinstall` workflow to make the correct things available.

/cc @benbayard @chaseadamsio @coopy

**Comment by benbayard** [comment]
I think dependency management is the most important feature to worry about, for now. However, it is an extremely complex topic and I understand that, right now, it only "works" by npm3 doing some magic. 

The answer could be as simple as a builder task `builder install`. It takes a field in your package.json called "upstreamDependencies" and runs `npm install` on each of them for the version you specify. Then the upstream can depend on them. 

The answer could be as complex as writing our own complete npm replacement.

**Comment by benbayard** [comment]
Another idea:

Add a `consumes` to the `.builderrc`. The consumes would be an archetype type that can be used by the upstream utilities. If you "consume" an archetype you get _all_ the archetypes dependencies available to it. 

The requirement for _both_ of these is that the consumer is a builder project. Is that something we are willing to state? If it is not, are there any better ways to bundle the dependencies for non-builder projects?

**Comment by ryan-roemer** [comment]
**UPDATE**:  The solution we've chosen for https://github.com/FormidableLabs/builder/issues/107 which is simply a pattern of having:

```
archetype-dev/require.js
```

that contains just:

```
module.exports = require;
```

could be further extended to

```
archetype/require.js
```

could potentially give us _true app dependencies_ from the archetype wherein in your app code you just require like:

```
// App
var React = require("<archetype>/require")("react");

// Test
var sinon = require("<archetype-dev>/require")("sinon");
```

Not exactly sure how that translated to frontend via webpack, but my hunch is that's also workable even if implemented slightly differently in config.

**Comment by ryan-roemer** [comment]
UPDATE: We're going with the same solution as in https://github.com/FormidableLabs/builder/issues/107 (documentation and adding `require.js` to _prod_ archetypes as well as dev archetypes).
